// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFJa-JZasl2OwiGoXKelAC0YIZIoKkUzU',
    appId: '1:625138831327:android:cbe34ba0dfa136596ffe6a',
    messagingSenderId: '625138831327',
    projectId: 'expensetracker-d278d',
    storageBucket: 'expensetracker-d278d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSttIsJ_dXvIS0kRILnSh-4jMNU_tNpvE',
    appId: '1:625138831327:ios:2bab6c4a89db41726ffe6a',
    messagingSenderId: '625138831327',
    projectId: 'expensetracker-d278d',
    storageBucket: 'expensetracker-d278d.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkqelnIttoTftAdr4KWd949gpYLzwdXY8',
    appId: '1:625138831327:web:631ec68d4cb7f6ed6ffe6a',
    messagingSenderId: '625138831327',
    projectId: 'expensetracker-d278d',
    authDomain: 'expensetracker-d278d.firebaseapp.com',
    storageBucket: 'expensetracker-d278d.firebasestorage.app',
    measurementId: 'G-7HMGEL6DZY',
  );

}